
# Absolute Paths to fits files
eROSITA_file_path: /Users/admin/Documents/GitHub/Matched-Catalog-Analysis/src/data_raw/eRASS1_Main.v1.1.fits
EDFF_file_path: /Users/admin/Documents/GitHub/Matched-Catalog-Analysis/src/data_raw/DAWN_EDFF_DR1.fits
EDFN_file_path: /Users/admin/Documents/GitHub/Matched-Catalog-Analysis/src/data_raw/DAWN_EDFN_DR1.fits
CDFS_file_path: /Users/admin/Documents/GitHub/Matched-Catalog-Analysis/src/data_raw/LuoCDFS.fits


# Absolute Paths to Merged Catalogs
edff_cdfs_path: /Users/admin/Documents/GitHub/Matched-Catalog-Analysis/src/data_final/merged_catalog_edff_cdfs.csv
edff_erosita_path: /Users/admin/Documents/GitHub/Matched-Catalog-Analysis/src/data_final/merged_catalog_edff_erosita.csv

edff_sed_data: /Users/admin/Documents/GitHub/matched-catalog-analysis/src/data_final/matched_edff_sed_data.csv

# Processed data path
save_data_path: /Users/admin/Documents/GitHub/Catalog-Matching/src/datasets_preprocessed
input_catalogs_path: /Users/admin/Documents/GitHub/Matched-Catalog-Analysis/src/data_lyr/input_catalogs

# Search Parameters (Arcsec)
adj_flux_rad: 6.0 
match_search_rad: 5.0
background_inner_rad: 10.0
background_outer_rad: 30.0

# Matching Parameters
interpolation_bins: 21
